# Generated by Django 3.1.2 on 2020-10-25 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("picture", models.ImageField(upload_to="users/images/")),
                ("second_name", models.CharField(max_length=100)),
                ("cellphone", models.CharField(default="", max_length=20)),
                ("birthday", models.DateField(auto_now=True)),
                ("address", models.CharField(max_length=200)),
                ("pets", models.ManyToManyField(to="pets.Pet")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
