# Generated by Django 3.1.2 on 2020-10-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='users/images/')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('cellphone', models.IntegerField()),
                ('birthday', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('pets', models.ManyToManyField(to='pets.Pet')),
            ],
        ),
    ]
