# Generated by Django 3.1.2 on 2020-11-07 03:58

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201104_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='users/images/default.png', upload_to=users.models.change_path_and_rename_picture),
        ),
    ]
