# Generated by Django 3.1.2 on 2020-10-25 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("species", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("picture", models.ImageField(upload_to="pets/images/")),
                ("name", models.CharField(max_length=100)),
                ("birthday", models.DateField(auto_now=True)),
                ("color", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[("F", "Fêmea"), ("M", "Macho")], max_length=1
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[("P", "Pequeno"), ("M", "Médio"), ("G", "Grande")],
                        max_length=1,
                    ),
                ),
                (
                    "breed",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="species.breed",
                    ),
                ),
                (
                    "specie",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="species.specie",
                    ),
                ),
            ],
        ),
    ]
