# Generated by Django 3.1.2 on 2020-10-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='pets/images/')),
                ('name', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('specie', models.CharField(max_length=100)),
                ('race', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('F', 'Fêmea'), ('M', 'Macho')], max_length=1)),
                ('size', models.CharField(choices=[('P', 'Pequeno'), ('M', 'Médio'), ('G', 'Grande')], max_length=1)),
            ],
        ),
    ]
