# Generated by Django 3.1.2 on 2020-10-25 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("species", "0001_initial"),
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="breed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="species.breed"
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="specie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="species.specie"
            ),
        ),
    ]
